#!/usr/bin/env python3
"""Generate/check the tracked GitHub distribution; canonical skills stay in .agents/skills."""
from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from pathlib import Path

from build import bundle_readme, copy_skill, target_manifest
from plugin_bundles import (BundleError, artifact_inventory, dump_json, read_json,
                            validate_composition, validate_schema_parity)

MARKETPLACE = "agentic-gamedev-skills"
DISPLAY_NAME = "Agentic Game Development Skills"
# Publication order and identities are deliberate; membership/metadata live in compositions.
LINEUP = ("one-button-game-builder", "gameplay-debugging-toolkit",
          "retro-arcade-game-finisher", "godot-mini-game-builder",
          "web-mini-game-kit", "agent-workflow-engineering")
CATALOGS = (".agents/plugins/marketplace.json", ".agents/plugins/api_marketplace.json",
            ".claude-plugin/marketplace.json")


def safe_path(repo: Path, relative: str) -> Path:
    path = Path(relative)
    if path.is_absolute() or ".." in path.parts:
        raise BundleError(f"path escape: {relative}")
    current = repo
    for part in path.parts:
        current = current / part
        if current.is_symlink():
            raise BundleError(f"symlink is not allowed: {current}")
    if not current.resolve().is_relative_to(repo.resolve()):
        raise BundleError(f"path escape: {relative}")
    return current


def compositions(repo: Path) -> list[dict]:
    directory = safe_path(repo, "plugin-bundles")
    expected = {f"{slug}.json" for slug in LINEUP} | {"schema.json"}
    if {p.name for p in directory.glob("*.json")} != expected:
        raise BundleError("publication requires exactly the six lineup compositions and schema.json")
    validate_schema_parity(safe_path(repo, "plugin-bundles/schema.json"))
    safe_path(repo, ".agents/skills")
    safe_path(repo, "LICENSE")
    result = []
    for slug in LINEUP:
        data = read_json(safe_path(repo, f"plugin-bundles/{slug}.json"))
        validate_composition(data, repo)
        if data["slug"] != slug or set(data["targets"]) != {"codex", "claude"}:
            raise BundleError(f"composition identity/dual-target mismatch: {slug}")
        result.append(data)
    if any(data["author"] != result[0]["author"] for data in result):
        raise BundleError("marketplace owner must match all composition authors")
    return result


def catalogs(data: list[dict]) -> dict[str, dict]:
    codex = {
        "name": MARKETPLACE, "interface": {"displayName": DISPLAY_NAME},
        "plugins": [{"name": item["slug"],
                     "source": {"source": "local", "path": f"./plugins/{item['slug']}"},
                     "policy": {"installation": "AVAILABLE", "authentication": "ON_INSTALL"},
                     "category": item["targets"]["codex"].get("category", "Developer Tools")}
                    for item in data],
    }
    # Both audiences get identical skill-only payloads. Separate names avoid collisions.
    api = {**codex, "name": f"{MARKETPLACE}-api"}
    claude = {
        "name": MARKETPLACE, "owner": data[0]["author"],
        "metadata": {"description": "Game development and agent workflow skills by abagames."},
        "plugins": [{"name": item["slug"], "source": f"./plugins/{item['slug']}",
                     "description": item["description"], "strict": True} for item in data],
    }
    # Versions belong in plugin manifests only; the drift gate checks both against composition.
    return dict(zip(CATALOGS, (codex, api, claude)))


def write_tree(repo: Path, stage: Path, data: list[dict]) -> None:
    for item in data:
        root = stage / "plugins" / item["slug"]
        root.mkdir(parents=True)
        for skill in item["skills"]:
            copy_skill(repo / ".agents/skills" / skill, root / "skills" / skill)
        shutil.copyfile(repo / "LICENSE", root / "LICENSE")
        (root / "LICENSE").chmod(0o644)
        for target in ("codex", "claude"):
            dump_json(root / f".{target}-plugin/plugin.json", target_manifest(item, target))
        readme = bundle_readme(item, "codex").replace("Target: codex", "Targets: Codex and Claude Code")
        readme += ("\n## Repository distribution\n\n"
                   "This directory is generated by `tools/plugin-bundles/published.py --write`. "
                   "Edit the source composition and canonical skills, then regenerate. "
                   "The repository drift check verifies every file and executable bit.\n")
        (root / "README.md").write_text(readme, encoding="utf-8")
    for relative, catalog in catalogs(data).items():
        dump_json(stage / relative, catalog)


def preflight(repo: Path, allow_missing: bool) -> None:
    root = safe_path(repo, "plugins")
    if root.exists():
        if not root.is_dir():
            raise BundleError("plugins must be a directory")
        actual = {p.name for p in root.iterdir()}
        if actual - set(LINEUP) or (not allow_missing and actual != set(LINEUP)):
            raise BundleError("missing/extra published plugin roots")
        for child in root.iterdir():
            if child.is_symlink() or not child.is_dir():
                raise BundleError(f"invalid plugin root: {child}")
            # Inspect before replacing anything; never follow a user-added symlink.
            artifact_inventory(child)
    elif not allow_missing:
        raise BundleError("missing published plugins tree")
    for relative in CATALOGS:
        path = safe_path(repo, relative)
        if path.exists() and not path.is_file():
            raise BundleError(f"catalog must be a file: {relative}")


def check_catalogs(repo: Path, data: list[dict]) -> None:
    for relative, expected in catalogs(data).items():
        catalog = read_json(safe_path(repo, relative))
        if catalog != expected:
            raise BundleError(f"catalog drift (identity, membership, metadata or source): {relative}")
        for entry in catalog["plugins"]:
            source = entry["source"]
            relative_root = source if isinstance(source, str) else source["path"]
            root = safe_path(repo, relative_root)
            if not root.is_dir() or root.name != entry["name"]:
                raise BundleError(f"catalog source does not resolve to plugin: {relative_root}")


def published(repo: Path, write: bool = False) -> None:
    data = compositions(repo)
    preflight(repo, allow_missing=write)
    with tempfile.TemporaryDirectory(prefix="published-plugins-") as temporary:
        stage = Path(temporary)
        write_tree(repo, stage, data)
        if write:
            # All sources and destinations have passed preflight; only generated locations change.
            for slug in LINEUP:
                destination = repo / "plugins" / slug
                if destination.exists():
                    shutil.rmtree(destination)
                shutil.copytree(stage / "plugins" / slug, destination)
            for relative in CATALOGS:
                destination = repo / relative
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(stage / relative, destination)
                destination.chmod(0o644)
        check_catalogs(repo, data)
        for slug in LINEUP:
            actual = artifact_inventory(repo / "plugins" / slug)
            expected = artifact_inventory(stage / "plugins" / slug)
            # artifact_inventory reserves plugin-lock.json for archive builds; never allow it here.
            if (repo / "plugins" / slug / "plugin-lock.json").exists():
                raise BundleError(f"unexpected archive lock in published root: {slug}")
            if actual != expected:
                changed = sorted(name for name in actual.keys() | expected.keys()
                                 if actual.get(name) != expected.get(name))
                raise BundleError(f"published payload drift: {slug}: {', '.join(changed[:8])}")
        for relative in CATALOGS:
            path = repo / relative
            if path.read_bytes() != (stage / relative).read_bytes() or path.stat().st_mode & 0o111:
                raise BundleError(f"catalog bytes/mode drift: {relative}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[2])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate tracked roots and catalogs")
    mode.add_argument("--check", action="store_true", help="reject any difference from canonical inputs")
    args = parser.parse_args()
    try:
        published(args.repo.resolve(), args.write)
    except (BundleError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print("ok: six published plugin roots and three catalogs match canonical inputs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
